
version: '3'
services:
  nessie:
    image: projectnessie/nessie:latest
    ports:
      - 19120
    depends_on:
      - dynamodb
    environment:
      - NESSIE_VERSION_STORE_DYNAMO_INITIALIZE=true
      - NESSIE_VERSION_STORE_TYPE=DYNAMO
      - QUARKUS_DYNAMODB_ENDPOINT_OVERRIDE=http://dynamodb:8000
      - QUARKUS_DYNAMODB_AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    depends_on:
      - dynamodb
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=xxx
      - AWS_SECRET_ACCESS_KEY=xxx
  dynamodb:
    image: amazon/dynamodb-local
    ports:
        - 8000
  spark:
    build: .
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - NESSIE_ENDPOINT=http://nessie:19120/api/v1